### ISSUE TITLE
Support for (systematic) variation of mutation rates across loci?

### ISSUE THREAD

**Issue by andrewparkermorgan** [statgenlmu/coala#161]
Does `coala` provide a means for setting locus-specific mutation rates?  I think `par_variation()` is close to what I want, only I would prefer to specify the deviation from the parent parameter rather than drawing it from a gamma distribution.

This would be useful for simulating, for instance, an autosomal and a sex-chromosome locus -- which have different effective population sizes -- in the same scenario.  My specific interest is in using `coala` in an ABC pipeline for estimating the ratio between the two locus-specific thetas.

If you can provide some guidance on a possible implementation, I am happy to write something up and submit a pull request.

**Comment by paulstaab** [comment]
No, at the moment `coala` does not support this, but I agree that this would be a useful feature. It would be useful to optimally restrict parameters (or even features) for a specific group of loci. I will look into it next week and keep you updated.

**Comment by paulstaab** [comment]
I guess getting this right is going to be a little more work that I anticipated, and I will only have time to work on it after my PhD defense next week. Sorry for the delay.

**Comment by paulstaab** [comment]
Sorry for the delay here. Implementing this requires some changes that I wanted to make anyway. I am currently in the process of implementing them in branch `group_features`. I'm almost done there, but only have very little time at the moment.

**Comment by paulstaab** [comment]
This is now possible with the latest development version, see #181. I'll submit a new CRAN release soon, so that the options also become available in the official version. I'm closing this issue for now.
