### ISSUE TITLE
Time intervals in Coala and changing growth rates

### ISSUE THREAD

**Issue by arjunbr93** [statgenlmu/coala#185]
I am wondering what exactly the time intervals mean in a coalescent model.

For example, setting growth of a population at time 0,
+ feat_growth(2, population = "all", time = "2", locus_group = "all")

Is this setting the growth rate of 2 from the second generation backwards in time, or forwards?

Similarly, what does time = "0.5" denote?
+ feat_growth(2, population = "all", time = "0.5", locus_group = "all")

Is this applying the growth rate at the time-point of 0.5 generations ago, or the time at which half simulation is completed?

For clarification, I am interested in letting a population grow to its maximum size via exponential growth and then setting growth rate to 0. Would the following accomplish that?
+ feat_growth(2, population = "all", time = "0", locus_group = "all")
+ feat_growth(0, population = "all", time = "1", locus_group = "all")

Alternatively, is there a way to use sfs data from a simulated model (with exponential growth) and use it   as a starting point in another model (no growth)?

**Comment by paulstaab** [comment]
All times in coala are in coalescent time units (I should really point that out in the documetation, sorry), e.g. 1 correspondents to 2 * N0 generations, where N0 usually is defined as the present day number of haploids in the first population. 

Coalescent theory in general assumes that N0 is large, and doesn't really allow meaningful derivations for things that happen within one generation. If that is your goal, better use an forward-in-time simulator.

If you use that two feat_growth commands, the population has its maximal size at present day (time 0) and its minimal size at times >=1, where the size is constant. Between times 1 and 0, the size grows exponentially (looking forwards in time). Is that what you want to achieve?

**Comment by arjunbr93** [comment]
Thanks for the reply.

What I want to do is have a population grow exponentially and achieve the final size in the first half and then have it at static growth, accumulating mutations, for the rest of the time.

So based on what you have suggested, would the following feat_growth commands do the trick?

+ feat_growth(2, population = "all", time = "0", locus_group = "all")
+ feat_growth(0, population = "all", time = "0.5", locus_group = "all")

**Comment by paulstaab** [comment]
@arjunbr93 Do you want the population to grow when looking forward in time? In your model, the population size at time 0.5 is smaller than at time 0. As indented, it stays constant at times more in the past than 0.5

**Comment by arjunbr93** [comment]
Yes, that is what I want to do.
So have the population grow from a single individual to the size of 100000 with growth rate of 2, and then have it stay constant for the second half of the simulation.

**Comment by paulstaab** [comment]
I think we are talking past each other here. Coalescent simulators start the simulation in the present (time 0), and then go back in time (time > 0). When looking at the model you describe forward in time, a constant population starts to grow 0.5 coalescent time units ago and keeps on growing until the present.

**Comment by arjunbr93** [comment]
Ah, I see.

So then if I set the growth rates as per following:

    feat_growth(2, population = "all", time = "1", locus_group = "all") +
    feat_growth(0, population = "all", time = "0.5", locus_group = "all")

Looking forward in time, the population will begin to grow exponentially at 1 coalescent time unit ago, and then switch to constant growth at 0.5 coalescent time unit ago.

Then, if I wanted to do the same with a large population size (100000 for example) at present, it seems like the timepoints need to be set to a much higher value for it to be anything meaningful.

**Comment by paulstaab** [comment]
Yes, that should do what you want :-)

I'm closing this issue, fell free to reopen it in case you have more questions.
