### ISSUE TITLE
as.segsites

### ISSUE THREAD

**Issue by rebzzy** [statgenlmu/coala#192]
Hi - I'm trying to use the as.segsites function to convert ms output and it does not appear to be working.

In ms:
./ms 4 1 -t 5 > test.out

In R:
```
test <- readMS("test.out") # with PopGenome
ss <- as.segsites(test)
ss # returns list()
is.segsites(ss) # returns false

```

**Comment by paulstaab** [comment]
Import from PopGenome and `as.segsites` will be removed from coala with version 0.6.0. I am closing this issue.
