### ISSUE TITLE
Coalescent trees as output?

### ISSUE THREAD

**Issue by alicemchardy** [statgenlmu/coala#193]
Is there a way to obtain coalescent trees for specific model settings?

**Comment by paulstaab** [comment]
Yes, using `sumstat_trees()`

**Comment by alicemchardy** [comment]
thanks, perfect. I found it now also in the documentation.

**Comment by dlaehnemann** [comment]
Hi @paulstaab,

thanks for pointing to the `sumstat_trees()` function. I have a follow-up question:

We would like to get both a tree and the leaf node DNA sequences out of the same simulation, but the coala package documentation for `sumstat_dna()` says that:
> It can not be calculated together with other summary statistics

Do I understand correctly, that for a given simulation, the tree output and the leaf node DNA sequences output are mutually exclusive? I.e. as both are summary statistics, that when specifying `+ sumstat_dna()`, we cannot also specify `sumstat_trees()`?

And if so, could we get around this by specifying the same model twice: once with `sumstat_trees()` specified and once with `sumstat_dna()` specified. We could run the two (almost) identical simulation setups with the same `seed` value, but would this give corresponding results?

Best regards,
David

**Comment by paulstaab** [comment]
I will also add a feature request for outputting the trees, but I will definitely not be able to integrate this into coala before middle of August, sorry.

**Comment by dlaehnemann** [comment]
Hi @paulstaab,

thanks for the clarifications and for trying this out -- it confirms my understanding.

As we will be integrating this into a bigger pipeline and had already opted not to use seq-gen (, as we will be interested in indels in the future, we will probably just go for using individual tools separately -- i.e. do what coala does in independent pipeline steps
