### ISSUE TITLE
Can Coala simulate population structure?

### ISSUE THREAD

**Issue by alicemchardy** [statgenlmu/coala#197]

**Comment by paulstaab** [comment]
Yes, see Section "Multiple Populations" in
https://cran.r-project.org/web/packages/coala/vignettes/coala-intro.html

Am Fr., 6. Juli 2018 um 10:56 Uhr schrieb Alice McHardy <
notifications@github.com>:

**Comment by dswdejonge** [comment]
If you're looking to simulate population structure with migration between many different populations, you might end up doing a lot of copy-paste of the feat_migration function. Someone gave me a good solution for this on stackoverflow: 
[https://stackoverflow.com/questions/54042332/how-to-automatically-set-up-and-add-functions-to-a-model-in-r] 

Perhaps the possibility to include a migration matrix might be a nice addition for the package?
