### ISSUE TITLE
coala package removed from CRAN repository

### ISSUE THREAD

**Issue by adityagilra** [statgenlmu/coala#213]
The package has been removed from the CRAN repository:
https://cran.r-project.org/web/packages/coala/index.html
so, this can be no longer installed using
install.packages("coala")

Do you know when the package will be added again?
And if not soon, then could you provide some instructions on alternate ways to install this on various OSs?

Thanks!

**Comment by DirkMetzler** [comment]
I have submitted a new version of the package on 13. December, and I hope that the it will soon appear on CRAN.

Best,
Dirk

**Comment by adityagilra** [comment]
Thanks Dirk, looking forward to it.
Best,
Aditya.

**Comment by DirkMetzler** [comment]
good news: coala is now back on CRAN
Best,
Dirk
